---
title: "Meshコードの地図を作成する"
author: "Shinya Uryu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(eval = TRUE, message = FALSE, warning = FALSE)
```

```{r loading_pkg, message = FALSE, error = FALSE}
library(celestial)
library(broom)
library(rvest)
# library(Nippon)
library(rgdal)
library(readr)
library(geojsonio)
library(ggplot2)
library(pforeach) # devtools::install_github("hoxo-m/pforeach")
library(dplyr)
```

## 第１次地域区画（4桁の地域メッシュコード）

* jpmesh_1_limit.geojson... 枠
* jpmesh_1.geojson... １次メッシュでのメッシュコード領域

少しずれるメッシュがあるので修正が必要

経度の間隔... 40分、緯度の間隔... １度

```{r set_parameter}
# 緯度経度の範囲
lon_range <- c(122, 154)
lat_range <- c(20, 46)
# １次メッシュの間隔
int1_lat  <- dms2deg("+0d40m00.00s", sep = "dms") # latitude
int1_lon <- dms2deg("+1d00m00.00s", sep = "dms") # longitude
seq1_lon <- seq(lon_range[1], lon_range[2], int1_lon)
seq1_lat <- seq(lat_range[1], lat_range[2], int1_lat)
# # ２次メッシュの間隔
int2_lat <- dms2deg("+0d05m00.00s", sep = "dms") # latitude
int2_lon <- dms2deg("+0d07m30.00s", sep = "dms") # longitude
seq2_lon <- seq(lon_range[1], lon_range[2] + int2_lon, int2_lon)
seq2_lat <- seq(lat_range[1], lat_range[2] + int2_lat, int2_lat)
```

```{r}
pforeach(i     = seq1_lon,
         .c    = rbind)(
           {
             data_frame(long  =  c(i, i, i + int1_lon, i + int1_lon, i))
           }) -> df_long

df_tmp <- data_frame(lat = rep(c(seq1_lat[2], seq1_lat[1], seq1_lat[1], seq1_lat[2], seq1_lat[2]), length(seq1_lon))) %>% 
  bind_cols(df_long)

df_res <- pforeach(i = 1:39, .c = rbind)({
  dplyr::mutate(df_tmp, 
                lat = lat + int1_lat * i) %>% 
    rbind(df_tmp)
}) %>% dplyr::mutate(group = rep(1:(nrow(.) / 5), each = 5))

df_tmp <- df_res %>% dplyr::group_by(group) %>% 
  dplyr::summarise(code2     = as.numeric(min(lat) * 1.5),
                   code4     = min(long) %>% substr(2, 3) %>% as.numeric(),
                   code_1_20 = paste0(code2, code4))

df_res %<>% inner_join(df_tmp) %>% 
  dplyr::select(long, lat, code_1_20) %>% 
  dplyr::rename(group = code_1_20) %>% 
  dplyr::filter(group <= 6854) # 6848
# dim(df_res) # [1] 12705     3
```

```{r save_geo_json, eval = TRUE}
df_res %>% mutate(group = as.character(group)) %>% 
geojson_json(input    = ., 
             group    = "group", 
             lon      = "long", 
             lat      = "lat", 
             geometry = "polygon") %>%
  geojson_write(input = .,
                         file = "../inst/jpmesh_1_sq_range.geojson",
                         group = "group",
                        geometry = "polygon")
```

-----

```{r confirm_data, eval = FALSE}
# 枠だけの図（領域外を含む正方形）
jp_map <- readOGR(dsn              = "../inst/jpmesh_1_sq_range.geojson",
                  layer            = "OGRGeoJSON",
                  stringsAsFactors = FALSE) %>% 
  tidy()

ggplot() + 
  geom_map(data = jp_map, 
           map  = jp_map,
           aes(x = long, y = lat, map_id = id), 
           fill = "white", color = "black",
           size = 0.5) + 
  coord_map() + 
  ggthemes::theme_map()
```

----

### 該当メッシュの抽出

```{r step1, eval = TRUE}
# このファイルも別途作成しておく事
names_1_20 <- vector()
code_1_20 <- vector()
url <- "http://www.gsi.go.jp/MAP/NEWOLDBL/200000/index200000.html" %>% read_html()
html_nodes(url, css = "map area") %>% {
  names_1_20 <<- html_attr(., "alt") %>% Nippon::kana2roma(.)
  code_1_20  <<- html_attr(., "href") %>% 
    sub(pattern = "/MAP/HISTORY/5-25-", replacement = "", x = .) %>% 
    sub(".html$", "", .)
}

df_mesh <- data_frame(names_1_20, code_1_20)
# Source: local data frame [130 x 2]
# 
#         names_1_20 code_1_20
#              (chr)     (chr)
# 1        shibetoro      6848
# 2          bettobu      6748
# 3            shana      6747
rm(list = grep("20$|url", ls(), value = TRUE))
```

１次メッシュコードから緯度経度を割り振る

* 南端緯度 * 1.5 (ex. 5438の場合、36 * 1.5... 54 / 1.5)
* 西端経度の下２桁 (ex. 5437の場合、38 + 100)

```{r tmp_step2, eval=FALSE}
df_mesh %>% tidyr::extract(col = code_1_20, into = c("code_1_20_12", "code_1_20_34"), remove = FALSE,
                           regex = "(\\d{2})(\\d{2})") %>% 
  dplyr::mutate(code_1_20_12 = as.numeric(code_1_20_12) / 1.5,
                code_1_20_34 = as.numeric(code_1_20_34) + 100) -> tmp

tmp %>% filter(code_1_20 == "5438")
# 138から139を、44.66667 から45.33333（差0.66666）を８当分
tmp2 <- expand.grid(
           long = tidyr::seq_range(min(tmp$code_1_20_34):max(tmp$code_1_20_34), 7 * 26),
           lat = seq(min(tmp$code_1_20_12), max(tmp$code_1_20_12), by = (0.66666 / 7)) %>% rep(34))
  # group_by(long) %>% 
  # mutate(long.x = seq(0, 7, 1),
  #        lat.y  = seq(0, 7, 1)) %>% 
  # ungroup() %>% 
  dplyr::mutate(code_1_20_12 = lat)
  
    dplyr::summarise(code2     = round(as.numeric(min(lat) * 1.5), 2),
                   code4     = as.numeric(substr(min(long), 2, 3)),
                   code_1_20 = paste0(code2, code4))
```


```{r save_geo_json, eval = FALSE}
dplyr::filter(df_res, group %in% df_mesh$code_1_20) %>% 
  geojson_json(input    = ., 
             group    = "group", 
             lat      = "lat", 
             lon      = "long", 
             geometry = "polygon") %>%
  geojson_write(input = .,
                         file = "../inst/jpmesh_1.geojson", # 
                         group = "group",
                        geometry = "polygon")
```

```{r confirm_data, eval = FALSE}
jp_map <- readOGR(dsn              = "../inst/jpmesh_1.geojson", 
                  layer            = "OGRGeoJSON",
                  stringsAsFactors = FALSE)

centroid <- coordinates(jp_map) %>% data.frame()
centroid$code_1_20 <- jp_map$group
colnames(centroid) <- c("long", "lat", "code_1_20")

## step1 で作成したdf_mesh
df_mesh %>% merge(centroid) %>% tbl_df() %>% 
  readr::write_csv(path = "../inst/jp_mesh_1.csv")

jp_map %<>% tidy()

ggplot() + 
  geom_map(data = jp_map, 
           map  = jp_map,
           aes(x = long, y = lat, map_id = id), 
           fill = "white", color = "black",
           size = 0.5) + 
  coord_map() + 
  ggthemes::theme_map()
```

```{r}
devtools::session_info()
```
