---
title: "Construct maps with jpmesh"
author: "Shinya Uryu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Construct maps with jpmesh}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE, 
  message = FALSE
)
```

```{r, load_employed_pkgs}
library(magrittr)
library(jpmesh)
library(sf)
library(purrr)
```

```{r}
df_polys <- meshcode_set(mesh_size = "80km") %>% 
  tibble::tibble("mesh" = .) %>% 
  dplyr::mutate(geometry = purrr::pmap(., ~ export_mesh(mesh = ..1) %>% 
                                    sf::st_as_text())) %>% 
  tidyr::unnest() %>% 
  dplyr::mutate(geometry = st_as_sfc(geometry)) %>% 
  st_sf()
```

## base

```{r, eval = FALSE, echo = TRUE}
df_polys %>% 
  st_geometry() %>% 
  plot()
```

## ggplot2

```{r, include = FALSE}
if (compareVersion(as.character(packageVersion("ggplot2")), 
               "2.2.1.9000") > 0) {
  devtools::install_github("tidyverse/ggplot2", ref = "39e4a3b")
}
```

```{r}
# Use develop version (2.2.1.9000)
library(ggplot2)
ggplot() + 
  geom_sf(data = df_polys, fill = NA) +
  geom_text(data = df_polys %>% dplyr::mutate(
    CENTROID = map(geometry, st_centroid),
    COORDS = map(CENTROID, st_coordinates),
    COORDS_X = map_dbl(COORDS, 1),
    COORDS_Y = map_dbl(COORDS, 2)    
  ),
    aes(COORDS_X, COORDS_Y, label = mesh), 
    size = 1.2, min.segment.length = 0) +
  coord_sf(datum = NA) +
  theme_void()
```

## leaflet

```{r, eval = FALSE, echo = TRUE}
library(leaflet)
leaflet() %>% 
  addTiles() %>% 
  addPolygons(data = df_polys)
```

## plotly

wip...

```{r sessioninfo}
sessionInfo()
```
